"""APRS symbol table lookup."""
from __future__ import annotations

# (symbol_table_char, symbol_code_char) -> human-readable name
# Primary table uses "/", alternate table uses "\\".
# Overlay characters (0-9, A-Z as the table char) overlay on the alternate table.
_SYMBOL_NAMES: dict[tuple[str, str], str] = {
    # Primary table (/)
    ("/", "!"): "Police",
    ("/", "#"): "Digipeater",
    ("/", "$"): "Telephone",
    ("/", "%"): "DX Cluster",
    ("/", "&"): "HF Gateway",
    ("/", "'"): "Small Aircraft",
    ("/", "("): "Mobile Satellite",
    ("/", ")"): "Wheelchair",
    ("/", "*"): "Snowmobile",
    ("/", "+"): "Red Cross",
    ("/", ","): "Boy Scouts",
    ("/", "-"): "House",
    ("/", "."): "X Mark",
    ("/", "/"): "Dot",
    ("/", "0"): "Circle (0)",
    ("/", "1"): "Circle (1)",
    ("/", "2"): "Circle (2)",
    ("/", "3"): "Circle (3)",
    ("/", "4"): "Circle (4)",
    ("/", "5"): "Circle (5)",
    ("/", "6"): "Circle (6)",
    ("/", "7"): "Circle (7)",
    ("/", "8"): "Circle (8)",
    ("/", "9"): "Circle (9)",
    ("/", ":"): "Fire",
    ("/", ";"): "Campground",
    ("/", "<"): "Motorcycle",
    ("/", "="): "Railroad Engine",
    ("/", ">"): "Car",
    ("/", "?"): "Server",
    ("/", "@"): "Hurricane",
    ("/", "A"): "Aid Station",
    ("/", "B"): "BBS",
    ("/", "C"): "Canoe",
    ("/", "E"): "Eyeball",
    ("/", "F"): "Farm Vehicle",
    ("/", "G"): "Grid Square",
    ("/", "H"): "Hotel",
    ("/", "I"): "TCP/IP",
    ("/", "K"): "School",
    ("/", "L"): "PC User",
    ("/", "M"): "MacAPRS",
    ("/", "N"): "NTS Station",
    ("/", "O"): "Balloon",
    ("/", "P"): "Police Car",
    ("/", "R"): "Recreational Vehicle",
    ("/", "S"): "Satellite",
    ("/", "T"): "SSTV",
    ("/", "U"): "Bus",
    ("/", "V"): "ATV",
    ("/", "W"): "NWS Site",
    ("/", "X"): "Helicopter",
    ("/", "Y"): "Yacht",
    ("/", "Z"): "WinAPRS",
    ("/", "["): "Jogger",
    ("/", "\\"): "DF Triangle",
    ("/", "]"): "PBBS",
    ("/", "^"): "Large Aircraft",
    ("/", "_"): "Weather Station",
    ("/", "`"): "Dish Antenna",
    ("/", "a"): "Ambulance",
    ("/", "b"): "Bike",
    ("/", "c"): "Command Post",
    ("/", "d"): "Fire Dept",
    ("/", "e"): "Horse",
    ("/", "f"): "Fire Truck",
    ("/", "g"): "Glider",
    ("/", "h"): "Hospital",
    ("/", "i"): "IOTA",
    ("/", "j"): "Jeep",
    ("/", "k"): "Truck",
    ("/", "l"): "Laptop",
    ("/", "m"): "Mic-E Repeater",
    ("/", "n"): "Node",
    ("/", "o"): "EOC",
    ("/", "p"): "Dog",
    ("/", "r"): "Repeater",
    ("/", "s"): "Power Boat",
    ("/", "t"): "Truck Stop",
    ("/", "u"): "18-Wheeler",
    ("/", "v"): "Van",
    ("/", "w"): "Water Station",
    ("/", "y"): "Yagi Antenna",
    ("/", "z"): "Shelter",
    # Alternate table (\)
    ("\\", "!"): "Emergency",
    ("\\", "#"): "Number",
    ("\\", "$"): "Bank",
    ("\\", "("): "Cloudy",
    ("\\", "*"): "Snow",
    ("\\", "+"): "Church",
    ("\\", "-"): "House (Alt)",
    ("\\", "/"): "Waypoint",
    ("\\", ":"): "Haze",
    ("\\", ";"): "Park",
    ("\\", "="): "Train",
    ("\\", "?"): "Info Kiosk",
    ("\\", "@"): "Hurricane (Alt)",
    ("\\", "B"): "Blowing Snow",
    ("\\", "C"): "Coast Guard",
    ("\\", "D"): "Drizzle",
    ("\\", "E"): "Smoke",
    ("\\", "F"): "Freezing Rain",
    ("\\", "G"): "Snow Shower",
    ("\\", "H"): "Fog",
    ("\\", "I"): "Rain Shower",
    ("\\", "J"): "Lightning",
    ("\\", "K"): "Kenwood",
    ("\\", "L"): "Lighthouse",
    ("\\", "N"): "Nav Buoy",
    ("\\", "O"): "Rocket",
    ("\\", "P"): "Parking",
    ("\\", "Q"): "Earthquake",
    ("\\", "R"): "Restaurant",
    ("\\", "S"): "Satellite (Alt)",
    ("\\", "T"): "Thunderstorm",
    ("\\", "U"): "SUV",
    ("\\", "W"): "NWS Site (Alt)",
    ("\\", "["): "Wall Cloud",
    ("\\", "]"): "Geocache",
    ("\\", "^"): "Aircraft",
    ("\\", "_"): "Weather Station (Alt)",
    ("\\", "`"): "Rain",
    ("\\", "a"): "ARRL",
    ("\\", "b"): "Blowing Dust",
    ("\\", "c"): "Civil Defense",
    ("\\", "e"): "Sleet",
    ("\\", "f"): "Funnel Cloud",
    ("\\", "g"): "Gale",
    ("\\", "h"): "Ham Store",
    ("\\", "i"): "Box / POI",
    ("\\", "j"): "Work Zone",
    ("\\", "k"): "Special Vehicle",
    ("\\", "m"): "Milepost",
    ("\\", "n"): "Small Circle",
    ("\\", "p"): "Partly Cloudy",
    ("\\", "r"): "Restrooms",
    ("\\", "s"): "Boat (Alt)",
    ("\\", "t"): "Tornado",
    ("\\", "u"): "Truck (Alt)",
    ("\\", "v"): "Van (Alt)",
    ("\\", "w"): "Flooding",
    ("\\", "x"): "Obstruction",
    ("\\", "y"): "Skywarn",
    ("\\", "z"): "Shelter (Alt)",
}


def aprs_symbol_name(symbol_table: str, symbol_code: str) -> str:
    """Return a human-readable name for an APRS symbol.

    For overlay symbols (table char is 0-9 or A-Z), the symbol is looked up in
    the alternate table and the overlay character is appended.
    Falls back to the raw two-character string if the symbol is not in the table.
    """
    is_overlay = symbol_table not in ("/", "\\")

    if is_overlay:
        name = _SYMBOL_NAMES.get(("\\", symbol_code))
        if name:
            return f"{name} (overlay: {symbol_table})"
        return f"\\{symbol_code} (overlay: {symbol_table})"

    name = _SYMBOL_NAMES.get((symbol_table, symbol_code))
    return name if name else f"{symbol_table}{symbol_code}"
